stages:
  - build
  - test
  - deploy


build:
  stage: build
  script:
    - echo "Building $APP_NAME"
    - apt-get update -qy  # Update package lists
    - apt-get install -y python3-pip  # Install pip
    - pip install -r requirements.txt  # Install Python dependencies
    - python manage.py migrate  # Apply database migrations
    # Add any other build-related commands here

unittest:
  stage: test
  script:
    - echo "Running unittests for $APP_NAME"
    - coverage run manage.py test  # Run unit tests with coverage
    - coverage report
    # Add any other test-related commands here

deploy:
  stage: deploy
  script:
    - echo "Deploying $APP_NAME"
    # Add your actual deployment commands here
